INSERT INTO livros (titulo, categoria, disponivel, ano_publicacao, autor_id) VALUES
('Dom Casmurro', 'Romance', TRUE, 1899, 1),
('Memórias Póstumas de Brás Cubas', 'Romance', TRUE, 1881, 1),
('A Hora da Estrela', 'Romance', TRUE, 1977, 2),
('1984', 'Ficção Distópica', FALSE, 1949, 3),
('A Revolução dos Bichos', 'Fábula', TRUE, 1945, 3),
('O Hobbit', 'Fantasia', FALSE, 1937, 4),
('O Senhor dos Anéis', 'Fantasia', TRUE, 1954, 4),
('Harry Potter e a Pedra Filosofal', 'Fantasia', FALSE, 1997, 5),
('Harry Potter e a Câmara Secreta', 'Fantasia', TRUE, 1998, 5),
('O Iluminado', 'Terror', TRUE, 1977, 6),
('It: A Coisa', 'Terror', TRUE, 1986, 6),
('Assassinato no Expresso do Oriente', 'Suspense', TRUE, 1934, 7),
('O Código Da Vinci', 'Suspense', FALSE, 2003, 8),
('Anjos e Demônios', 'Suspense', TRUE, 2000, 8),
('Sapiens', 'História', TRUE, 2011, 9),
('Homo Deus', 'História', TRUE, 2015, 9),
('O Pequeno Príncipe', 'Infantil', TRUE, 1943, 10),
('Cidadela', 'Romance', TRUE, 1948, 10),
('Carrie', 'Terror', TRUE, 1974, 6),
('Animais Fantásticos', 'Fantasia', TRUE, 2001, 5);